{% set name = "qbatch" %}
{% set version = "2.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/qbatch-{{ version }}.tar.gz
  sha256: 3771f198d34504c8115dbb396413305f91333859d4c96b5a64d6f39e807a540a

build:
  entry_points:
    - qbatch=qbatch:qbatchParser
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - future
    - imp

test:
  imports:
    - qbatch
  commands:
    - pip check
    - qbatch --help
  requires:
    - pip

about:
  home: https://github.com/pipitone/qbatch
  summary: Execute shell command lines in parallel on Slurm, S(un|on of) Grid Engine (SGE) and PBS/Torque clusters
  license: Unlicense
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jaeakle
